// <auto-generated />
using System;
using InstantMessenger.Friendships.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstantMessenger.Friendships.Infrastructure.Database.Migrations
{
    [DbContext(typeof(FriendshipsContext))]
    [Migration("20201107113542_Init Friendships")]
    partial class InitFriendships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Friendships")
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstantMessenger.Friendships.Domain.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("FriendshipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FirstPerson")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SecondPerson")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Friendships");

                    b.HasIndex("FirstPerson");

                    b.HasIndex("SecondPerson");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("InstantMessenger.Friendships.Domain.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("InvitationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Invitations");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("InstantMessenger.Friendships.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Persons");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("InstantMessenger.Friendships.Domain.Friendship", b =>
                {
                    b.HasOne("InstantMessenger.Friendships.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("FirstPerson")
                        .HasConstraintName("FK_FirstPerson_Friendships_Persons")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InstantMessenger.Friendships.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("SecondPerson")
                        .HasConstraintName("FK_SecondPerson_Friendships_Persons")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InstantMessenger.Friendships.Domain.Invitation", b =>
                {
                    b.HasOne("InstantMessenger.Friendships.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK_Receiver_Invitations_Persons")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InstantMessenger.Friendships.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Sender_Invitations_Persons")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
