name: Angular

on: 
  workflow_dispatch:
env:
  PACKAGES_TOKEN: ${{secrets.PACKAGES_TOKEN}}
  AZURE_RESOURCE_GROUP: instantmessenger
  AZURE_APP_PLAN: instantmessenger
  AZURE_LOCATION: '"westeurope"'
  AZURE_WEBAPP_NAME: instantmessengerweb
jobs:  
  build:
    runs-on: ubuntu-latest
    
    steps:
      - 
        uses: actions/checkout@v2
        name: Clone repository
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: https://index.docker.io/v1
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: src/InstantMessenger.Web/ClientApp
         file: ./Dockerfile
         push: true
         tags: ${{secrets.DOCKERHUB_USERNAME}}/instantmessengerweb:latest     
     
