name: Angular

on: 
  workflow_dispatch:
env:
  PACKAGES_TOKEN: ${{secrets.PACKAGES_TOKEN}}
  AZURE_RESOURCE_GROUP: instantmessenger
  AZURE_APP_PLAN: instantmessenger
  AZURE_LOCATION: '"westeurope"'
  AZURE_WEBAPP_NAME: instantmessengerweb
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repo
          uses: actions/checkout@v2        
        -
          name: Build and Push
          id: docker_build
          uses: docker/build-push-action@v1          
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            tag_with_ref: true
            path: ./src/InstantMessenger.Web/ClientApp
            dockerfile: ./src/InstantMessenger.Web/ClientApp/Dockerfile
            repository: ${{ secrets.DOCKERHUB_USERNAME }}/instantmessengerweb
