name: .NET Core

on: 
  push:
    branches: master
  workflow_dispatch:
env:
  PACKAGES_TOKEN: ${{secrets.PACKAGES_TOKEN}}
  AZURE_RESOURCE_GROUP: instantmessenger
  AZURE_APP_PLAN: instantmessenger
  AZURE_LOCATION: '"westeurope"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: instantmessenger
  #################################################  
  ############### AZURE SQLDATABASE  ##############
  AZURE_DATABASE_SERVER: instantmessenger
  AZURE_DATABASE: instantmessengerdb
  #################################################
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    -
      uses:   actions/checkout@v1
      name:   Setup .NET core
    -
      uses:   actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - 
      name:  Build with dotnet
      run:  dotnet build --configuration Release
  publish_image:
    name: Publish Image
    runs-on: ubuntu-latest

    steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        -
          name: Build and Push
          id: docker_build
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            tag_with_ref: true
            repository: ${{ secrets.DOCKERHUB_USERNAME }}/chatting_app
                        
  deploy:
    runs-on: ubuntu-latest  
    name: 'Deploy to Azure Containers Instances'
    
    steps:
      - name: 'Login'
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - uses: azure/docker-login@v1
        with:
          login-server: https://index.docker.io/v1/
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: 'Deploy'
#         uses: 'azure/aci-deploy@v1'
#         with:
#           resource-group: ${{secrets.RESOURCE_GROUP}}
#           dns-name-label: ${{secrets.RESOURCE_GROUP}}${{github.run_number}}
#           image: ${{secrets.REGISTRY_LOGIN_SERVER}}/${{secrets.DOCKERHUB_USERNAME}}/chatting-app
#           name: instant-messenger
#           location: 'west europe'
      
      - name: Deploy web app container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/chatting_app
