name: Update database

on: 
  pull_request:
    types: [labeled]
env:
  PACKAGES_TOKEN: ${{secrets.PACKAGES_TOKEN}}
  AZURE_RESOURCE_GROUP: instantmessenger
  AZURE_APP_PLAN: instantmessenger
  AZURE_LOCATION: '"westeurope"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: instantmessenger
  #################################################  
  ############### AZURE SQLDATABASE  ##############
  AZURE_DATABASE_SERVER: instantmessenger
  AZURE_DATABASE: instantmessengerdb
  #################################################
jobs:  
  setup-up-azure-resources:
    if: contains(github.event.pull_request.labels.*.name, 'migrate database')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use production connection string
        uses: microsoft/variable-substitution@v1
        with:
          files: 'src/InstantMessenger.Api/appsettings.json'
        env:
          ConnectionStrings.InstantMessengerDb: "Server=tcp:${{env.AZURE_DATABASE_SERVER}}.database.windows.net,1433;Initial Catalog=${{AZURE_DATABASE}};Persist Security Info=False;User ID=${{secrets.AZURE_DATABASE_LOGIN}};Password={secrets.AZURE_DATABASE_PASSWORD};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      - name: Dump Appsettings.json
        run: |
          cat src/InstantMessenger.Api/appsettings.json
      - name: Run dotnet tools
        run: |
          dotnet tool install --global dotnet-ef --version 3.1.9
          pwd
          dotnet ef dbcontext list --project src/InstantMessenger.Api
